# Generated by Django 4.1.3 on 2022-11-19 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('send_usermail', models.EmailField(max_length=254, unique=True)),
                ('reciver_usermail', models.EmailField(max_length=254, unique=True)),
                ('invoiceno', models.CharField(max_length=21)),
                ('item_description', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
