# Generated by Django 4.1.3 on 2022-11-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='CreateInvoice',
        ),
    ]
